[workspace]
members = [
  "01_02_why_async",
  "01_04_async_await_primer",
  "03_01_async_await",
  "05_01_streams",
  "05_02_iteration_and_concurrency",
  "06_02_join",
  "06_03_select",
  "07_05_recursion",
  "09_01_sync_tcp_server",
]
